// =============================================================
// FILE: src/integrations/rtk/tags.ts
// RTK Query cache/tag listesi
// =============================================================

export const metahubTags = [
  'Auth',
  'User',
  'AdminUsers',
  'Profiles',
  'Profile',
  'UserRoles',
  'UserRole',
  'SiteSettings',
  'SiteSettingsBulk',
  'CustomPages',
  'CustomPageSlug',
  'CustomPage',
  'Faqs',
  'Services',
  'MenuItems',
  'MenuItem',
  'MenuItemPublic',
  'Slider',
  'Sliders',
  'Contacts',
  'FooterSections',
  'FooterSectionsBySlug',
  'Mail',
  'MailAccounts',
  'MailInbox',
  'Newsletter',
  'Notifications',
  'Notification',
  'Reviews',
  'Review',
  'Storage',
  'Health',
  'Resources',
  'History',
  'Subscriptions',
  'Orders',
  'Order',
  'Popups',
  'Banners',
  'Banner',
  'AmazonQuota',
  'AmazonScanJob',
  'AmazonHistory',
  'ByokKey',
  'DecisionMakerJobs',
  'DecisionMakerResults',
  'OutreachLists',
  'Entitlements',
  'CrmDashboard',
  'CrmAccounts',
  'CrmContacts',
  'CrmDeals',
  'CrmActivities',
  'CrmProducts',
  'CrmQuotes',
  'CrmOrders',
  'CrmDocuments',
  'CrmTasks',
  'CrmReminders',
  'LeadCandidates',
  'LeadJobs',
  'FairCatalog',
  'IcpProfiles',
  'LeadRules',
  'LeadFeedback',
  'OutreachCampaigns',
  'OutreachDrafts',
  'MarketTargets',
  'MarketLeads',
  'MarketSignals',
  'MarketStats',
  'MarketReports',
  'CrmMailSummary',
  'CrmReportsSummary',
  'CrmUsersSummary',
  'CrmBusinessSummary',
  'WorkspaceUsers',
  'WorkspaceUserModules',
] as const;

export type MetahubTag = (typeof metahubTags)[number];
