CREATE TABLE IF NOT EXISTS `user_mail_accounts` (
  `id` char(36) NOT NULL,
  `tenant_key` varchar(64) NOT NULL DEFAULT 'avrasya',
  `owner_user_id` char(36) NOT NULL,
  `provider` enum('gmail_oauth','imap_smtp') NOT NULL DEFAULT 'gmail_oauth',
  `email` varchar(255) NOT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `enc_access_token` text DEFAULT NULL,
  `enc_refresh_token` text DEFAULT NULL,
  `token_expiry` datetime(3) DEFAULT NULL,
  `scopes` text DEFAULT NULL,
  `imap_host` varchar(255) DEFAULT NULL,
  `imap_port` int DEFAULT NULL,
  `smtp_host` varchar(255) DEFAULT NULL,
  `smtp_port` int DEFAULT NULL,
  `smtp_secure` tinyint(1) DEFAULT NULL,
  `smtp_username` varchar(255) DEFAULT NULL,
  `enc_password` text DEFAULT NULL,
  `status` enum('connected','expired','error','disconnected') NOT NULL DEFAULT 'connected',
  `last_error` varchar(500) DEFAULT NULL,
  `last_synced_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_mail_account_email` (`tenant_key`, `owner_user_id`, `email`),
  KEY `idx_user_mail_accounts_owner` (`tenant_key`, `owner_user_id`),
  KEY `idx_user_mail_accounts_provider` (`tenant_key`, `provider`, `status`),
  CONSTRAINT `fk_user_mail_accounts_owner`
    FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
