CREATE TABLE IF NOT EXISTS `storage_assets` (
  `id` char(36) NOT NULL,
  `user_id` char(36) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `bucket` varchar(64) NOT NULL,
  `path` varchar(512) NOT NULL,
  `folder` varchar(255) DEFAULT NULL,
  `mime` varchar(127) NOT NULL,
  `size` bigint unsigned NOT NULL,
  `width` int unsigned DEFAULT NULL,
  `height` int unsigned DEFAULT NULL,
  `url` text DEFAULT NULL,
  `hash` varchar(64) DEFAULT NULL,
  `provider` varchar(16) NOT NULL DEFAULT 'cloudinary',
  `provider_public_id` varchar(255) DEFAULT NULL,
  `provider_resource_type` varchar(16) DEFAULT NULL,
  `provider_format` varchar(32) DEFAULT NULL,
  `provider_version` int unsigned DEFAULT NULL,
  `etag` varchar(64) DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_bucket_path` (`bucket`, `path`),
  KEY `idx_storage_user` (`user_id`),
  KEY `idx_storage_bucket` (`bucket`),
  KEY `idx_storage_user_bucket` (`user_id`, `bucket`),
  KEY `idx_storage_folder` (`folder`),
  KEY `idx_storage_created` (`created_at`),
  KEY `idx_provider_pubid` (`provider_public_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
